### ISSUE TITLE
Cannot build go/proc on Mac OS X

### ISSUE THREAD

**Issue by andrewwebber** [tgulacsi/go#1]

**Comment by tgulacsi** [comment]
Please provide some details: I have no Mac at hand.

**Comment by andrewwebber** [comment]
# github.com/tgulacsi/go/proc
src/github.com/tgulacsi/go/proc/procutils.go:74: undefined: procAttrSetGroup
src/github.com/tgulacsi/go/proc/procutils.go:120: undefined: Pkill
src/github.com/tgulacsi/go/proc/procutils.go:123: undefined: Pkill
src/github.com/tgulacsi/go/proc/procutils.go:134: undefined: GroupKill
src/github.com/tgulacsi/go/proc/procutils.go:137: undefined: GroupKill
src/github.com/tgulacsi/go/proc/procutils.go:159: undefined: isGroupLeader

**Comment by tgulacsi** [comment]
Please try 1c05d43, hope it is better.

**Comment by andrewwebber** [comment]
Its 'go gettable', looks good. Truly grateful
